project:
    type: website
    output-dir: cursusmateriaal
    render:
    - "*.qmd"
    - "!./exercises/day_2/solutions/"
    - "!./exercises/day_2/create/"
title-slide-attributes:
    data-background-opacity: "0.5"
    data-background-size: cover
website:
    title: "LLMs for Data Science"
author: "Alex van Vorstenbosch"
institute: ""
date: "Februari 2025"
format:
    revealjs:
        width: 1600
        height: 1000
        slide-number: true
        chalkboard: 
            buttons: false
        preview-links: true 
        theme: 
            - night 
            - ./style.scss
        scrollable: false
        highlight-style: oblivion
        code-copy: true
        incremental: true  
execute:
    warning: false
    error: false
    cache: true
resources:
    - ./slides/day_1/demo/
    - ./slides/webpages/*
    - ./slides/webpages/breaking the algorithm_files 
    - ./slides/webpages/ChatGPT for Data Science_files 
    - ./slides/webpages/Example of using Wolfram Alpha plugin_files 
    - ./slides/webpages/Glitchtokens example behaviour_files 
    - ./slides/webpages/hallucination1_files 
    - ./slides/webpages/hallucination2_files 
    - ./slides/webpages/Hello world!_files 
    - ./slides/webpages/Prime Numbers Multiplication_files 
    - ./slides/webpages/Prompt Engineering in NLP_files 
    - ./slides/webpages/Three Prime Numbers Multiplied_files
