project:
  output-dir: slides

title-slide-attributes:
  data-background-opacity: "0.5"
  data-background-size: cover
institute: ""
format:
    revealjs:
        width: 1600
        height: 1000
        slide-number: true
        chalkboard: 
            buttons: false
        preview-links: true 
        theme: night 
        scrollable: false
        css: style.scss
        highlight-style: oblivion
        code-copy: true
        incremental: true  
    html:
        css: style.scss
        highlight-style: oblivion
        code-copy: true
        theme:
          light: flatly
          dark: darkly
execute:
    warning: false
    error: false
    cache: true
jupyter: openai
