project:
  output-dir: _slides

title-slide-attributes:
  data-background-opacity: "0.5"
  data-background-size: cover
institute: ""
date: "11-17-2023"
format:
    revealjs:
        width: 1600
        height: 1000
        slide-number: true
        chalkboard: 
            buttons: false
        preview-links: true 
        theme: night 
        scrollable: false
        css: style.scss
        highlight-style: oblivion
        code-copy: true
        
execute:
    warning: false
    error: false
    cache: true
